spring:
  config:
    activate:
      on-profile: local-lambda

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mupol-test
    username: root
    password: password

  redis:
    host: localhost
    port: 6379

cloud:
  aws:
    credentials:
      accessKey: AKIAQJYEOLNYD7VDGONA
      secretKey: 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
    s3:
      bucket: mupol-raw-media
    region:
      static: ap-northeast-2
    stack:
      auto: false
    cloudfront:
      domain: https://dl8zw9uzq9w9c.cloudfront.net

ffmpeg:
  path:
    base: ffmpeg
    ffprobe: ffprobe
    upload: /Users/byunghak/Documents/intellij_workspace/Mupol-Server/src/main/resources/upload/
